on:
  push:
    branches: ["main"] # Trigger on push to main branch
    paths:
      - "packages/react-app/**" # Only trigger for changes in this folder
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: read # To checkout code
  pages: write # To deploy to Pages
  id-token: write # To verify deployment source

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install and Build
        working-directory: ./packages/react-app
        run: |
          npm install
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./packages/react-app/dist" # Path to your static files (e.g., './dist' for frameworks)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
